apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: attr_default-gem
  title: AttrDefault
  description: Dynamic Ruby defaults for ActiveRecord attributes
  tags:
    - ruby
    - gem
    - private
    - rails-dependent
  annotations:
    buildkite.com/project-slug: Invoca/attr_default
    github.com/project-slug: Invoca/attr_default
    invoca.com/version-repository-location: rubygems
    invoca.com/version-repository-name: attr_default
spec:
  type: library
  lifecycle: production
  owner: octothorpe
  dependsOn: []
