---
name: Pipeline
on: [push]
jobs:
  tests:
    uses: Invoca/ruby-test-matrix-workflow/.github/workflows/ruby-test-matrix.yml@main
    secrets: inherit
    with:
      test-command: "bundle exec rake"
