---
name: Update Appraisals
on:
  push: ~
  schedule:
  - cron: '0 13 * * 0' # Every Sunday at 1PM UTC
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Update Appraisal Gemfiles
      run: bundle install && bundle exec appraisal install
    - name: Commit & Push changes
      run: |
        git config --global user.name 'Invoca Automation'
        git config --global user.email 'octothorpe@users.noreply.github.com'
        git commit -am "non-production: Update Appraisal Gemfiles" || exit 0
        git push
